image:
  file: .gitpod.dockerfile

tasks:
    - before: nvm install 20.15.1 && nvm use 20.15.1
      init: npm install
      command: npm run start-server

ports:
    - port: 8080
      onOpen: open-preview
