name: Sync fork with upstream

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop
      - name: Sync with upstream
        run: |
          git remote add upstream "https://github.com/TriliumNext/Notes.git"
          git fetch upstream develop
          git checkout develop
          git merge "upstream/develop" --ff-only
          git push origin develop
